import java
from micronaut.test.extensions.junit5.annotation import MicronautTest
from org.junit.jupiter.api import Disabled, Test

from .Elephant import Elephant
from .Person4 import Person4, Title


# TODO(python): the sourcegen annotation visitors need a SourceGenerator for Language.PYTHON (all tests of this suite pass with a local one delegating to JavaPoetSourceGenerator)
@Disabled("TODO(python): micronaut-sourcegen registers no SourceGenerator for VisitorContext.Language.PYTHON yet, so the annotation visitors skip Python classes and the generated types do not exist (unchanged with micronaut-core 5.2.4: `KeyError: host symbol micronaut.sourcegen.docs....<Generated> is not defined`)")
@MicronautTest(startApplication=False)
class ObjectTest:
    # tag::test[]
    @Test
    def test_to_string(self) -> None:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        Person4Object = java.type("micronaut.sourcegen.docs.objects.Person4Object")
        person = Person4(123, Title.MR, "Cédric", bytes([1, 2, 3]))

        assert Person4Object.toString(person) is not None
        assert "Person4[" in str(person)
        assert str(person) == "Person4[id=123, title=MR, name=Cédric, data=[1, 2, 3]]"

    # end::test[]

    # tag::testt[]
    @Test
    def test_multiple_dimension_arrays(self) -> None:
        elephant = Elephant("Daisy", 5, False, [[1] * 3] * 3)
        elephant_diff = Elephant("Daisy", 5, False, [[2] * 3] * 3)
        elephant_same = Elephant("Dumbo", 5, False, [[1] * 3] * 3)

        assert hash(elephant) != hash(elephant_diff)
        assert hash(elephant) == hash(elephant_same)

    @Test
    def test_equals_with_exclude(self) -> None:
        elephant = Elephant("Daisy", 5, False, [[1] * 3] * 3)
        elephant_diff = Elephant("Daisy", 5, False, [[2] * 3] * 3)
        elephant_same = Elephant("Dumbo", 5, False, [[1] * 3] * 3)

        assert elephant != elephant_diff
        assert elephant == elephant_same

    @Test
    def test_equals_with_correct_objects(self) -> None:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        Person4Object = java.type("micronaut.sourcegen.docs.objects.Person4Object")
        person = Person4(123, Title.MR, "Cédric", bytes([1, 2, 3]))
        person_same = Person4(123, Title.MR, "Cédric", bytes([1, 2, 3]))
        person_diff_primitive = Person4(124, Title.MR, "Cédric", bytes([1, 2, 3]))
        person_diff_enum = Person4(123, Title.MRS, "Cédric", bytes([1, 2, 3]))
        person_diff_object = Person4(123, Title.MR, "Cédric Jr.", bytes([1, 2, 3]))
        person_diff_array = Person4(123, Title.MR, "Cédric", bytes([1, 2, 4]))

        assert Person4Object.equals(person, person_same) is not None

        assert person == person
        assert person == person_same

        assert person != person_diff_primitive
        assert person != person_diff_enum
        assert person != person_diff_object
        assert person != person_diff_array

    @Test
    def test_equals_with_nulls(self) -> None:
        person = Person4(123, Title.MR, "Cédric", bytes([1, 2, 3]))
        person_double_null1 = Person4(123, Title.MR, None, bytes([1, 2, 3]))
        person_double_null2 = Person4(123, Title.MR, None, bytes([1, 2, 3]))
        person_single_null = Person4(124, Title.MR, "Cédric", None)

        assert person != None  # noqa: E711
        assert person != object()

        assert person_double_null1 == person_double_null2
        assert person_single_null != person
        assert person != person_single_null

    @Test
    def test_hash_code_with_nulls(self) -> None:
        person = Person4(123, Title.MR, "Cédric", bytes([1, 2, 3]))
        person_double_null1 = Person4(123, Title.MR, None, bytes([1, 2, 3]))
        person_double_null2 = Person4(123, Title.MR, None, bytes([1, 2, 3]))
        person_single_null = Person4(124, Title.MR, "Cédric", None)

        assert hash(person_double_null1) == hash(person_double_null2)
        assert hash(person_single_null) != hash(person)
        assert hash(person) != hash(person_single_null)

    @Test
    def test_hash_code(self) -> None:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        Person4Object = java.type("micronaut.sourcegen.docs.objects.Person4Object")
        person = Person4(123, Title.MR, "Cédric", bytes([1, 2, 3]))
        person_same = Person4(123, Title.MR, "Cédric", bytes([1, 2, 3]))
        person_diff_primitive = Person4(124, Title.MR, "Cédric", bytes([1, 2, 3]))
        person_diff_enum = Person4(123, Title.MRS, "Cédric", bytes([1, 2, 3]))
        person_diff_object = Person4(123, Title.MR, "Cédric Jr.", bytes([1, 2, 3]))
        person_diff_array = Person4(123, Title.MR, "Cédric", bytes([1, 2, 4]))

        assert Person4Object.hashCode(person) is not None
        assert hash(person) == hash(person)
        assert hash(person) == hash(person_same)
        assert hash(person) != hash(person_diff_primitive)
        assert hash(person) != hash(person_diff_enum)
        assert hash(person) != hash(person_diff_object)
        assert hash(person) != hash(person_diff_array)
    # end::testt[]
