plugins {
    id("io.micronaut.build.internal.sourcegen-base")
    id("io.micronaut.build.internal.common")
}

dependencies {
    testRuntimeOnly(mnTest.junit.platform.launcher)
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

tasks.withType(Checkstyle).configureEach {
    enabled = false
}

repositories {
    mavenCentral()
}
dependencies {
    testRuntimeOnly(mnTest.junit.platform.suite)
}
