projectVersion=1.7.2
projectGroup=io.micronaut.sourcegen

title=Compilation time source code generators
projectDesc=Micronaut SourceGen exposes a language-neutral API for source code generation.
projectUrl=https://micronaut.io
githubSlug=micronaut-projects/micronaut-sourcegen
developers=Denis Stepanov

org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.configuration-cache.parallel=false
org.gradle.caching=true
org.gradle.parallel=true
kotlin.stdlib.default.dependency=false
