[versions]
managed-kotlinpoet = "2.2.0"

google-truth = "1.4.5"
google-compile-testing = "0.23.0"
google-jimfs = "1.3.1"
intellij-java-decompiler = "253.31033.145"

errorprone-gradle-plugin = "4.4.0"
error_prone_core = "2.45.0"
nullaway = "0.12.15"

managed-asm = "9.9.1"

micronaut = "5.0.0-M20"
micronaut-platform = "4.10.8"
micronaut-data = "5.0.0-M1"
micronaut-validation = "5.0.0-M1"
micronaut-gradle-plugin = "4.6.2"

[libraries]
# Micronaut
micronaut-core = { module = "io.micronaut:micronaut-core-bom", version.ref = "micronaut" }
micronaut-data = { module = "io.micronaut.data:micronaut-data-bom", version.ref = "micronaut-data" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

managed-kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "managed-kotlinpoet" }
managed-kotlinpoet-javapoet = { module = "com.squareup:kotlinpoet-javapoet", version.ref = "managed-kotlinpoet" }

managed-asm = { module = "org.ow2.asm:asm", version.ref = "managed-asm" }
managed-asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "managed-asm" }
managed-asm-util = { module = "org.ow2.asm:asm-util", version.ref = "managed-asm" }

gradle-errorprone = { module = "net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin", version.ref = "errorprone-gradle-plugin" }
error-prone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "error_prone_core" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }

# Testing
google-truth = { module = "com.google.truth:truth", version.ref = "google-truth" }
google-compile-testing = { module = "com.google.testing.compile:compile-testing", version.ref = "google-compile-testing" }
google-jimfs = { module = "com.google.jimfs:jimfs", version.ref = "google-jimfs" }
intellij-java-decompiler = { module = "com.jetbrains.intellij.java:java-decompiler-engine", version.ref = "intellij-java-decompiler" }

micronaut-gradle-plugin = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref="micronaut-gradle-plugin" }
