import java
from micronaut.test.extensions.junit5.annotation import MicronautTest
from org.junit.jupiter.api import Disabled, Test


# TODO(python): the sourcegen annotation visitors need a SourceGenerator for Language.PYTHON (all tests of this suite pass with a local one delegating to JavaPoetSourceGenerator)
@Disabled("TODO(python): micronaut-sourcegen registers no SourceGenerator for VisitorContext.Language.PYTHON yet, so the annotation visitors skip Python classes and the generated types do not exist")
@MicronautTest(startApplication=False)
class PersonBuilderTest:

    # tag::test[]
    @Test
    def builds_person(self) -> None:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        PersonBuilder = java.type("micronaut.sourcegen.docs.builder.PersonBuilder")
        person = PersonBuilder.builder() \
            .id(123) \
            .name("Cédric") \
            .data(bytes([1, 2, 3])) \
            .build()
        assert person.name == "Cédric"
        assert list(person.data) == [1, 2, 3]
        assert person.id == 123
    # end::test[]
