import java
from micronaut.test.extensions.junit5.annotation import MicronautTest
from org.junit.jupiter.api import Disabled, Test


# TODO(python): the sourcegen annotation visitors need a SourceGenerator for Language.PYTHON (all tests of this suite pass with a local one delegating to JavaPoetSourceGenerator)
@Disabled("TODO(python): micronaut-sourcegen registers no SourceGenerator for VisitorContext.Language.PYTHON yet, so the annotation visitors skip Python classes and the generated types do not exist (unchanged with micronaut-core 5.2.4: `KeyError: host symbol micronaut.sourcegen.docs....<Generated> is not defined`)")
@MicronautTest(startApplication=False)
class EmployeeStagedBuilderTest:

    # tag::test[]
    @Test
    def builds_employee(self) -> None:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        EmployeeStagedBuilder = java.type("micronaut.sourcegen.docs.stagedbuilder.EmployeeStagedBuilder")
        employee = EmployeeStagedBuilder.builder() \
            .name("Billy Bounce") \
            .age(33) \
            .employed(False) \
            .nickname("Billy") \
            .build()
        assert employee.name == "Billy Bounce"
        assert employee.age == 33
        assert employee.employed is False
        assert employee.nickname == "Billy"
    # end::test[]

    @Test
    def builds_employee_without_the_optional_properties(self) -> None:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        EmployeeStagedBuilder = java.type("micronaut.sourcegen.docs.stagedbuilder.EmployeeStagedBuilder")
        employee = EmployeeStagedBuilder.builder() \
            .name("Billy Bounce") \
            .age(33) \
            .employed(True) \
            .build()
        assert employee.name == "Billy Bounce"
        assert employee.nickname is None
