import java
from micronaut.test.extensions.junit5.annotation import MicronautTest
from org.junit.jupiter.api import Disabled, Test


# TODO(python): the sourcegen annotation visitors need a SourceGenerator for Language.PYTHON (verified locally with one)
@Disabled("TODO(python): micronaut-sourcegen has no SourceGenerator for VisitorContext.Language.PYTHON yet, so the annotation visitors skip Python classes and the generated types do not exist")
@MicronautTest(startApplication=False)
class AnimalSuperBuilderTest:

    # tag::test[]
    @Test
    def test_cat(self) -> None:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        CatSuperBuilder = java.type("micronaut.sourcegen.docs.superbuilder.CatSuperBuilder")
        cat = CatSuperBuilder.builder() \
            .name("MrPurr") \
            .age(2) \
            .bread("British") \
            .meowLevel(100) \
            .color("Red") \
            .build()

        assert cat.name == "MrPurr"
        assert cat.age == 2
        assert cat.bread == "British"
        assert cat.meowLevel == 100
        assert cat.color == "Red"

    @Test
    def test_dog(self) -> None:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        DogSuperBuilder = java.type("micronaut.sourcegen.docs.superbuilder.DogSuperBuilder")
        dog = DogSuperBuilder.builder() \
            .name("MrDog") \
            .age(3) \
            .bread("JackR") \
            .barkLevel(20) \
            .color("Blue") \
            .big(True) \
            .build()

        assert dog.name == "MrDog"
        assert dog.age == 3
        assert dog.bread == "JackR"
        assert dog.barkLevel == 20
        assert dog.color == "Blue"
        assert dog.big is True
    # end::test[]
