import java
from micronaut.test.extensions.junit5.annotation import MicronautTest
from org.junit.jupiter.api import Disabled, Test


# TODO(python): the sourcegen annotation visitors need a SourceGenerator for Language.PYTHON (all tests of this suite pass with a local one delegating to JavaPoetSourceGenerator)
@Disabled("TODO(python): micronaut-sourcegen registers no SourceGenerator for VisitorContext.Language.PYTHON yet, so the annotation visitors skip Python classes and the generated types do not exist (unchanged with micronaut-core 5.2.4: `KeyError: host symbol micronaut.sourcegen.docs....<Generated> is not defined`)")
@MicronautTest(startApplication=False)
class UserTest:

    # tag::test[]
    @Test
    def test_simple(self) -> None:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        UserSuperBuilder = java.type("micronaut.sourcegen.docs.singular.UserSuperBuilder")
        user = UserSuperBuilder.builder() \
            .id(123) \
            .name("Denis") \
            .role("READ") \
            .role("WRITE") \
            .property("key", "value") \
            .build()
        assert user.id == 123
        assert user.name == "Denis"
        assert list(user.roles) == ["READ", "WRITE"]
        assert dict(user.properties) == {"key": "value"}

    @Test
    def test_add_all(self) -> None:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        UserSuperBuilder = java.type("micronaut.sourcegen.docs.singular.UserSuperBuilder")
        user = UserSuperBuilder.builder() \
            .id(123) \
            .name("Denis") \
            .role("READ") \
            .role("WRITE") \
            .roles(["ROLES_ADMIN", "ROLES_USER"]) \
            .property("key", "value") \
            .properties({"key1": "value1", "key2": "value2"}) \
            .build()
        assert user.id == 123
        assert user.name == "Denis"
        assert list(user.roles) == ["READ", "WRITE", "ROLES_ADMIN", "ROLES_USER"]
        assert dict(user.properties) == {"key": "value", "key1": "value1", "key2": "value2"}

    @Test
    def test_clear(self) -> None:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        UserSuperBuilder = java.type("micronaut.sourcegen.docs.singular.UserSuperBuilder")
        user = UserSuperBuilder.builder() \
            .id(123) \
            .name("Denis") \
            .role("READ") \
            .role("WRITE") \
            .clearRoles() \
            .roles(["ROLES_ADMIN", "ROLES_USER"]) \
            .property("key", "value") \
            .clearProperties() \
            .properties({"key1": "value1", "key2": "value2"}) \
            .build()
        assert user.id == 123
        assert user.name == "Denis"
        assert list(user.roles) == ["ROLES_ADMIN", "ROLES_USER"]
        assert dict(user.properties) == {"key1": "value1", "key2": "value2"}
    # end::test[]
