# tag::clazz[]
from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Annotated

import java
from micronaut.sourcegen.annotations import EqualsAndHashCode, ToString

if TYPE_CHECKING:
    from micronaut.sourcegen.annotations.EqualsAndHashCode import Exclude as EqualsAndHashCodeExclude
    from micronaut.sourcegen.annotations.ToString import Exclude as ToStringExclude


@ToString
@EqualsAndHashCode
@dataclass(eq=False)
class Elephant:
    name: Annotated[str, EqualsAndHashCodeExclude]
    age: int = 0
    hasSibling: bool = False
    values: Annotated[list[list[int]], ToStringExclude] = field(default_factory=list)

    def __str__(self) -> str:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        return str(java.type("micronaut.sourcegen.docs.objects.ElephantObject").toString(self))

    def __eq__(self, other: object) -> bool:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        return bool(java.type("micronaut.sourcegen.docs.objects.ElephantObject").equals(self, other))

    def __hash__(self) -> int:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        return int(java.type("micronaut.sourcegen.docs.objects.ElephantObject").hashCode(self))
# end::clazz[]
