# tag::clazz[]
from enum import Enum

import java
from micronaut.sourcegen.annotations import EqualsAndHashCode, ToString


class Title(Enum):
    MRS = "MRS"
    MR = "MR"
    MS = "MS"


@ToString
@EqualsAndHashCode
class Person4:
    id: int
    title: Title
    name: str | None
    data: bytes

    def __init__(self, id: int, title: Title, name: str | None, data: bytes):
        self.id = id
        self.title = title
        self.name = name
        self.data = data

    def __str__(self) -> str:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        return str(java.type("micronaut.sourcegen.docs.objects.Person4Object").toString(self))

    def __eq__(self, other: object) -> bool:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        return bool(java.type("micronaut.sourcegen.docs.objects.Person4Object").equals(self, other))

    def __hash__(self) -> int:
        # TODO(python): generated by sourcegen, no shim until the Python source generator ships
        return int(java.type("micronaut.sourcegen.docs.objects.Person4Object").hashCode(self))
# end::clazz[]
